### ISSUE TITLE
internal wav file writer?

### ISSUE THREAD

**Issue by PaulBatchelor** [luvsound/libpippi#1]
Instead of having a dependency on SoX, why not include a library designed to write wav files?

Soundpipe uses dr_wav, which has proven to be quite reliable over the years:

https://github.com/mackron/dr_libs/blob/master/dr_wav.h

Tinywav is a smaller and IMO more readable solution, but I've had issues with it on Windows:

https://github.com/mhroth/tinywav

**Comment by hecanjog** [comment]
Yeah SoX is just there for testing the examples. In general I've been considering I/O as out of the scope of this library I think. At least that was my plan initially -- just do I/O in the host context, whatever the library is being used in. For the examples maybe wrapping a library like dr_wav would be better than SoX though!

**Comment by PaulBatchelor** [comment]
Yeah just using a WAV library for the local examples is suitable enough for me. I can help out with this, as I do have experience using dr_wav.

**Comment by hecanjog** [comment]
You got me thinking, I don't know why I was resisting providing i/o wrappers here... I just realized the author of dr_wav is the same as miniaudio, which I was planning to wrap for an SDL2-based project, and in those cases why not support an easy way to do that directly?

I'm happy to work on this too but if you want to add WAV writing support that would be very welcome!

**Comment by PaulBatchelor** [comment]
#2 fixes this
